[
    {
        registration_no: null,
        make: null,
        model: null,
        year_of_make: null,
        hire_purchase: null,
        finance_company: null,
        vehicle_purpose: "To ran errands",
        vehicle_consent: "no",
        driver_type: "friend",
        fullname: "Shane Papa Kwesi Mensah",
        address: "Ashongman, Accra",
        age: "21",
        occupation: "Developer",
        phone: "0503845965",
        drivers_license: "DR-92839283",
        license_issue_date: "2026-01-14",
        driver_fullname: "Eric Apaloo",
        driver_address: "Ashongman, Accra",
        driver_age: "26",
        driver_occupation: "Driver",
        driver_phone: "0241277284",
        driver_license: "DR-238287392",
        driver_license_date: "2026-02-09",
        driver_insurance_details: "Eric Apaloo, Ashongman",
        accident_date: "2026-03-12",
        accident_time: "17:10",
        exact_location: "Adenta",
        people_in_vehicle: "2",
        report_date: "Through text message",
        accident_description: "A car came from knowher and hit us",
        fault_person: "The drunk Driver",
        vehicle_damage: "Front Smashed to bits",
        damaged_vehicle_location: "Adentas",
        repairer_fullname: "Gideon",
        repairer_address: "Sackey",
        your_vehicle_injured:
            '[{"name":"","age":"","address":"","injuries":""}]',
        other_vehicle_injured:
            '[{"name":"","age":"","address":"","injuries":""}]',
        involved_vehicle_reg: "GD 7263-22",
        involved_vehicle_make: "OPEL",
        involved_vehicle_model: "VETRA",
        owner_fullname: "Francis Sackey",
        owner_address: "Adenta Commandos",
        owner_telephone: "0241277253",
        owner_policy: "P-1003-101-2026-000005",
        other_vehicle_damage: "Front smashed as well",
        claim_made: "no",
        claim_made_details: null,
        police_report: "yes",
        police_report_details: "At the time of the accident",
        officer_details: "Richard Adotey",
        indem_policy: "no",
        indem_policy_details: null,
        declaration_date: "2026-05-08",
        digital_signature: "Shane Papa Kwesi Mensah",
        declaration_agreement: "true",
    },

    {
        POLICY_SEQUENCE: "30381253",
        POLICY_NUMBER: "934",
        POLICY_OWNER: "24940",
        POLICY_INSURED: "24940",
        POLICY_BRANCH: "1002",
        POLICY_AGENT: "7118",
        POLICY_STATUS: "3",
        POLICY_STATUS_REASON: "5",
        POLICY_MAIN_CLASS: "2",
        POLICY_LOB: "20",
        POLICY_PRODUCT: "201",
        POLICY_COMMENCEMENT_DATE: "2021-02-12",
        POLICY_EXPIRY_DATE: "2024-04-26",
        POLICY_EFFECTIVE_DATE: "2023-04-27",
        POLICY_ENDORSEMENT_DATE: "2023-04-27",
        POLICY_TOTAL_PREMIUM: "673",
        POLICY_TOTAL_SI: "20000",
        POLICY_CURRENCY: "GHC",
        vehicle_number: null,
        motor_risks: [],
        status_label: "active",
        status_reason: "Renewal",
    },
    {
        POLICY_SEQUENCE: "30289095",
        POLICY_NUMBER: "P-203-1101-2022-000049",
        POLICY_OWNER: "21230",
        POLICY_INSURED: "21230",
        POLICY_STATUS: "3",
        POLICY_STATUS_REASON: "5",
        POLICY_CURRENCY: "GHC",
        POLICY_TOTAL_PREMIUM: "250",
        POLICY_TOTAL_SI: "0",
        POLICY_COMMENCEMENT_DATE: "2020-08-13",
        POLICY_EXPIRY_DATE: "2023-08-15",
        POLICY_EFFECTIVE_DATE: "2022-08-16",
        POLICY_ENDORSEMENT_DATE: "2022-08-16",
        POLICY_PRODUCT_ID: "203",
        POLICY_LOB_ID: "20",
        POLICY_MAIN_CLASS_ID: "2",
        POLICY_BRANCH_ID: "1101",
        POLICY_AGENT_ID: "30116",
        POLICY_PRODUCT_NAME: "MOTOR THIRD PARTY ONLY",
        POLICY_LOB_NAME: "MOTOR",
        POLICY_MAIN_CLASS_NAME: "MOTOR",
        POLICY_BRANCH_NAME: "KUMASI",
        POLICY_AGENT_NAME: " BAIDOO SELASI KWAMENA",
        vehicle_number: null,
        motor_risks: [],
        status_label: "active",
        status_reason: "Renewal",
    },
];
